

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=apigateway,sns,dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localnet

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      SNS: http://localstack:4566
      DYNAMODB: http://localstack:4566
    depends_on:
      - localstack
    ports:
      - "8080:8080"
    networks:
      - localnet

networks:
  localnet:
    driver: bridge